version: '3.8'

services:
  db:
    container_name: shortener-postgres
    image: postgres:15.4-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
      
  redis:
    container_name: shortener-redis
    image: redis:7.2.0-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - PASSWORD=${REDIS_PASSWORD}
    ports:
      - 6379:6379
    restart: always